version: '3.0'
services:
  searcharr:
    container_name: searcharr
    image: toddrob/searcharr:latest
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./settings.py:/app/settings.py
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - "9080:9080"
    healthcheck:
      test: ["CMD", "python3", "-c", "print('ok')"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
